name: +Mᐁ includes
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '**.md'
      - '!changelog.md'
      - 'osmfeula.txt'

jobs:
  includes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🤖 defaults
        uses: devlooped/actions-bot@v1
        with:
          name: ${{ secrets.BOT_NAME }}
          email: ${{ secrets.BOT_EMAIL }}
          gh_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          token: ${{ env.GH_TOKEN }}

      - name: +Mᐁ includes
        uses: devlooped/actions-includes@v1

      - name: 📝 OSMF EULA
        shell: pwsh
        run: |
          $file = "osmfeula.txt"
          $props = "src/Directory.Build.props"
          if (-not (test-path $file) -or -not (test-path $props)) {
            exit 0
          }

          $product = dotnet msbuild $props -getproperty:Product
          if (-not $product) { 
            write-error 'To use OSMF EULA, ensure the $(Product) property is set in Directory.props'
            exit 1
          }
          
          ((get-content -raw $file) -replace '\$product\$',$product).trim() | set-content $file

      - name: ✍ pull request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            **.md
            osmfeula.txt
          base: main
          branch: markdown-includes
          delete-branch: true
          labels: docs
          author: ${{ env.BOT_AUTHOR }}
          committer: ${{ env.BOT_AUTHOR }}
          commit-message: +Mᐁ includes
          title: +Mᐁ includes
          body: +Mᐁ includes
          token: ${{ env.GH_TOKEN }}
