name: sponsor 💜
on: 
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  sponsor:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      token: ${{ secrets.GH_TOKEN }}
    if: ${{ !endsWith(github.event.sender.login, '[bot]') && !endsWith(github.event.sender.login, 'bot') }}      
    steps:
      - name: 🤘 checkout
        if: env.token != ''
        uses: actions/checkout@v2
          
      - name: 💜 sponsor 
        if: env.token != ''
        uses: devlooped/actions-sponsor@main
        with:
          token: ${{ env.token }}
